import Head from 'next/head'
import { Inter } from 'next/font/google'
import axios from 'axios'
import ListProducts from '@/components/products/ListProducts'
import React from 'react'


const inter = Inter({ subsets: ['latin'] })



const Home = () => {
  const [productsData, setProductsData] = React.useState()
  React.useEffect(() => {
    const getProducts = async () => {
      try {
        // const { data } = await axios.get('https://fakestoreapi.com/products')
        const { data } = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/api/products`)
        setProductsData(data)
      }
      catch (error) {
        console.log(error)
      }
    }
    getProducts()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ListProducts data={productsData} />
      </main>
    </>
  )
}

export default Home